name: Deploy app node com github actions

on:
 push:
  branches:
   - main


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: action/checkout@v3

    - name: Configurar Docker
      uses: docker/setuo-buildx-action@v3

    - name: Build da imagem Docker
      run: docker build -t hello-worl-node .

    - name: Finalizar
      uses: echo "Build concluido. Render detectará o push e fará o deploy automaticamente"
